version: '3.8'

services:
  app:
    image: ghcr.io/your-username/your-repo:latest # Replace with your image name
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - app_network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
